config/routes.rb
L10nDashboard::Application.routes.draw do
  resources :projects
  root to: 'projects#index'

  

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show

  end



  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:component, :language, :new_changed_word, :total_word, :due_date, :project_manager, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			""
		end
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>L10N Dashboard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a href="#" class="brand">L10N Dashboard</a>
				<ul class="nav">
					<li><%= link_to "All Projects", projects_path %></li>
					<li class="dropdown">
              			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Run Engineering Tool <b class="caret"></b></a>
              			<ul class="dropdown-menu">
                			<li><a href="#">Create TMX</a></li>
                			<li><a href="#">Create Glossary</a></li>
                			<li><a href="#">Prepare TM for review</a></li>
               				<li class="divider"></li>
               				<li><a href="#">Get files from Perforce</a></li>
                			<li><a href="#">Checkin file to perforce</a></li>
                			<li><a href="#">Doing something else</a></li>
              			</ul>
            		</li>
				</ul>
				<form class="navbar-search pull-left" action="">
            <input type="text" class="search-query span2 GINGER_SOFATWARE_control" placeholder="Search Project" spellcheck="false" ginger_sofatware_editor="true" style="background-attachment: local; background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAAASCAYAAADczdVTAAAAaElEQVRoQ+3SMQ0AAAzDsJU/6cHI4xKoFHlnCoQFFn67VuAAhCAtAGCa3zmADKQFAEzzOweQgbQAgGl+5wAykBYAMM3vHEAG0gIApvmdA8hAWgDANL9zABlICwCY5ncOIANpAQDT/M4f2UwAEx3XHE4AAAAASUVORK5CYII=); position: relative; font-size: 13px; line-height: 13px; background-position: 10px 12px; background-repeat: no-repeat no-repeat;">
          </form>
			</div>
		</div>
	</div>

	<div class="container">
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<button class="close" data-dismiss="alert">×</button>
				<%= message %>
			</div>
		<% end %>
		    
		<%= yield %>
	</div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :component %><br>
    <%= f.text_field :component %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :new_changed_word %><br>
    <%= f.number_field :new_changed_word %>
  </div>
  <div class="field">
    <%= f.label :total_word %><br>
    <%= f.number_field :total_word %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :project_manager %><br>
    <%= f.text_field :project_manager %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="page-header">
  <h1>All of the Projects</h1>
</div>

<%= link_to "Create a new project", new_project_path, class: "btn btn-success" %>

<% @projects.each do |project| %>
  <div class="project">

   <strong><%= project.component %></strong>
   <p>Language:       <%= project.language %><br>
   New/Changed Words: <%= project.new_changed_word %><br>
   Total Words:       <%= project.total_word %><br>
   Due Date:          <%= project.due_date %><br>
   Project Manager:   <%= project.project_manager %><br>
   Status:            <%= project.status %><br>
   </p>
   <div class="meta">
        <%= link_to time_ago_in_words(project.created_at) + " ago", project %> 
        <span class="admin">
          | <%= link_to "Edit", edit_project_path(project) %> | 
          <%= link_to "Cancel", project, method: :delete, data: { confirm: "Are you sure your want to cancle this project?"} %>
        </span>
    </div>
  </div>

<% end %>

app/views/projects/new.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :component %><br>
    <%= f.text_field :component %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :project_manager %><br>
    <%= f.text_field :project_manager %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Component:</strong>
  <%= @project.component %>
</p>

<p>
  <strong>Language:</strong>
  <%= @project.language %>
</p>

<p>
  <strong>New changed word:</strong>
  <%= @project.new_changed_word %>
</p>

<p>
  <strong>Total word:</strong>
  <%= @project.total_word %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @project.due_date %>
</p>

<p>
  <strong>Project manager:</strong>
  <%= @project.project_manager %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>